## Tout sur les DataFrames avec Pandas

## Index partagé par toutes les colonnes

Les objets df peuvent intéragir facilement avec de nombreuses colonnes.

Chacune de ces colonnes est représentée par un objet Series.
Les objets Series gardent l'alignement entre valeurs et leurs intitulés d'index.

Pour les df qui sont une collection d'objets Series, ils gardent l'alignement entre colonnes et lignes.

Pandas partage un index de ligne pour plusieurs colonnes
Par défaut, cet index est représenté par des entiers (int)

On a donc un index partagé par toutes les colonnes. Résultat si on essaye de lire un fichier csv contenant un nombre d'éléments différents par colonne, cela retourne une erreur.

In [1]:
import pandas as pd

In [2]:
fandango = pd.read_csv("fandango_score_comparison.csv")

In [3]:
print(fandango.head(2))

                             FILM  RottenTomatoes  RottenTomatoes_User  \
0  Avengers: Age of Ultron (2015)              74                   86
1               Cinderella (2015)              85                   80

   Metacritic  Metacritic_User  IMDB  Fandango_Stars  Fandango_Ratingvalue  \
0          66              7.1   7.8             5.0                   4.5
1          67              7.5   7.1             5.0                   4.5

   RT_norm  RT_user_norm  ...  IMDB_norm  RT_norm_round  RT_user_norm_round  \
0     3.70           4.3  ...       3.90            3.5                 4.5
1     4.25           4.0  ...       3.55            4.5                 4.0

   Metacritic_norm_round  Metacritic_user_norm_round  IMDB_norm_round  \
0                    3.5                         3.5              4.0
1                    3.5                         4.0              3.5

   Metacritic_user_vote_count  IMDB_user_vote_count  Fandango_votes  \
0                        1330                271107           14846
1                         249                 65709           12640

   Fandango_Difference
0                  0.5
1                  0.5

[2 rows x 22 columns]

In [4]:
print(fandango.index)

RangeIndex(start=0, stop=146, step=1)

## Utiliser des index entiers pour sélectionner des lignes

In [5]:
# 5 premières lignes
fandango[0:5]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [6]:
# lignes 140 jusqu'à la dernière
fandango[140:]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
140,Inside Out (2015),98,90,94,8.9,8.6,4.5,4.5,4.90,4.50,...,4.30,5.0,4.5,4.5,4.5,4.5,807,96252,15749,0.0
141,Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.70,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
142,'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.10,...,3.60,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
143,"Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.90,...,3.70,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0
144,Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.90,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

In [7]:
# ligne d'index 50
fandango.iloc[50]

FILM                          Pitch Perfect 2 (2015)
RottenTomatoes                                    67
RottenTomatoes_User                               68
Metacritic                                        63
Metacritic_User                                  5.7
IMDB                                             6.7
Fandango_Stars                                   4.5
Fandango_Ratingvalue                             4.2
RT_norm                                         3.35
RT_user_norm                                     3.4
Metacritic_norm                                 3.15
Metacritic_user_nom                             2.85
IMDB_norm                                       3.35
RT_norm_round                                    3.5
RT_user_norm_round                               3.5
Metacritic_norm_round                              3
Metacritic_user_norm_round                         3
IMDB_norm_round                                  3.5
Metacritic_user_vote_count                       192
IMDB_user_vote_count                           56333
Fandango_votes                                  4577
Fandango_Difference                              0.3
Name: 50, dtype: object

In [8]:
# ligne d'index 45 et 90
fandango.iloc[[45,90]]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
45,Tomorrowland (2015),50,53,60,6.4,6.6,4.0,3.7,2.5,2.65,...,3.30,2.5,2.5,3.0,3.0,3.5,262,42937,8077,0.3
90,The SpongeBob Movie: Sponge Out of Water (2015),78,55,62,6.5,6.1,3.5,3.3,3.9,2.75,...,3.05,4.0,3.0,3.0,3.5,3.0,196,26046,4493,0.2

* Lire le dataset "fandango_score_comparison" dans le dataframe fandango ---- Fait plus haut.
* Retourner un DataFrame contenant seulement la première et la dernière ligne et assigner le résultat à la variable first_last.
* Afficher le résultat

In [9]:
first_last = fandango.iloc[[1, -1]]
first_last

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.00,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

## Utiliser des index personnalisés

In [10]:
# DataFrame.set_index(Series, inplace=True, drop=False)
#Par défaut, Pandas va créer un nouveau df et l'indexer avec les valeurs de la colonne spécifiée
# puis supprime la colonne utilisée pour le nouvel index.
# - Series : correspondra au nouvel index
# - inplace : si on spécifie la valeur true cela ne créera pas de nouveau df et ça va remplacer l'index du df d'origine par le nouveau correspondant à la colonne spécifiée en paramètre "Séries"
# - drop : la colonne spécifiée en paramètre "Series" sera conservée dans le df au lieu d'être supprimée.

* Utiliser la méthode set_index pour indéxer notre DataFrame fandango avec la colonne "FILM". A préciser que nous souhaitons conserver la colonne "FILM". De plus nous souhaitons garder le DataFrame d'origine et en créer un nouveau que nous assignerons à la variable fandango_films.
* Afficher l'index du DataFrame fandango_films à l'aide de l'attribut index.

In [11]:
fandango_films = fandango.set_index("FILM", drop=False)

In [12]:
print(fandango_films.index)

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

## Sélectionner des valeurs depuis un index personnalisé

In [13]:
# sélection avec crochets ou méthode loc[]
fandango_films["Mr. Holmes (2015)":"Two Days, One Night (2014)"]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.9,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
'71 (2015),'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.1,...,3.6,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
"Two Days, One Night (2014)","Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.9,...,3.7,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0

In [14]:
fandango_films.loc["Mr. Holmes (2015)":"Two Days, One Night (2014)"]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.9,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
'71 (2015),'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.1,...,3.6,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
"Two Days, One Night (2014)","Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.9,...,3.7,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0

In [15]:
#film spécifique
fandango_films.loc["Kumiko, The Treasure Hunter (2015)"]

FILM                          Kumiko, The Treasure Hunter (2015)
RottenTomatoes                                                87
RottenTomatoes_User                                           63
Metacritic                                                    68
Metacritic_User                                              6.4
IMDB                                                         6.7
Fandango_Stars                                               3.5
Fandango_Ratingvalue                                         3.5
RT_norm                                                     4.35
RT_user_norm                                                3.15
Metacritic_norm                                              3.4
Metacritic_user_nom                                          3.2
IMDB_norm                                                   3.35
RT_norm_round                                                4.5
RT_user_norm_round                                             3
Metacritic_norm_round                                        3.5
Metacritic_user_norm_round                                     3
IMDB_norm_round                                              3.5
Metacritic_user_vote_count                                    19
IMDB_user_vote_count                                        5289
Fandango_votes                                                41
Fandango_Difference                                            0
Name: Kumiko, The Treasure Hunter (2015), dtype: object

In [16]:
# Sélection depuis une liste de films
movies = ["Kumiko, The Treasure Hunter (2015)", "Danny Collins (2015)", "Ant-Man (2015)"]
fandango_films.loc[movies]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
"Kumiko, The Treasure Hunter (2015)","Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0
Danny Collins (2015),Danny Collins (2015),77,75,58,7.1,7.1,4.0,4.0,3.85,3.75,...,3.55,4.0,4.0,3.0,3.5,3.5,33,11206,531,0.0
Ant-Man (2015),Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.50,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5

Lorsque nous sélectionnons des lignes multiples, Pandas retourne un df. Et lorsque nous sélectionnons une seule ligne, Pandas retourne un objet Series à la place.

Dans les deux cas, Pandas conserve l'index d'origine, avec des entiers, même si nous avons spécifié un nouvel index. Ce qui signifie que l'on peut toujours sélectionner les lignes par les numéros (par les entiers, par l'ancien index)

Exo

* Sélectionner les films suivants depuis la DataFrame fandango_films (dans l'ordre suivant) et assigner les à la variable some_movies :
                * "Top Five (2014)"
                * "Black Sea (2015)"
                * "Taken 3 (2015)"
* Afficher le résultat.

In [19]:
some_movies = ["Top Five (2014)", "Black Sea (2015)", "Taken 3 (2015)"]
fandango_films.loc[some_movies]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Top Five (2014),Top Five (2014),86,64,81,6.8,6.5,4.0,3.5,4.30,3.2,...,3.25,4.5,3.0,4.0,3.5,3.5,124,16876,3223,0.5
Black Sea (2015),Black Sea (2015),82,60,62,6.6,6.4,4.0,3.5,4.10,3.0,...,3.20,4.0,3.0,3.0,3.5,3.0,37,16547,218,0.5
Taken 3 (2015),Taken 3 (2015),9,46,26,4.6,6.1,4.5,4.1,0.45,2.3,...,3.05,0.5,2.5,1.5,2.5,3.0,240,104235,6757,0.4

## Méthode Apply() sur les colonnes d'un DataFrame

In [20]:
# apply()
# permet d'appliquer une fonction sur les objets Series d'un df

In [21]:
# dataframe.apply(lambda x: x**2)
# cela retournerait un nouveau df en ayant élevé à la puissance 2 chaque élément des colonnes numériques

In [22]:
import numpy as np

In [23]:
#retourner les types de données en tant que Series

In [24]:
types = fandango_films.dtypes

In [25]:
types

FILM                           object
RottenTomatoes                  int64
RottenTomatoes_User             int64
Metacritic                      int64
Metacritic_User               float64
IMDB                          float64
Fandango_Stars                float64
Fandango_Ratingvalue          float64
RT_norm                       float64
RT_user_norm                  float64
Metacritic_norm               float64
Metacritic_user_nom           float64
IMDB_norm                     float64
RT_norm_round                 float64
RT_user_norm_round            float64
Metacritic_norm_round         float64
Metacritic_user_norm_round    float64
IMDB_norm_round               float64
Metacritic_user_vote_count      int64
IMDB_user_vote_count            int64
Fandango_votes                  int64
Fandango_Difference           float64
dtype: object

In [28]:
# filtrer les nombres à virgules float64 et retourner le nom des colonnes
float_columns = types[types.values == "float64"].index
float_columns

Index(['Metacritic_User', 'IMDB', 'Fandango_Stars', 'Fandango_Ratingvalue',
       'RT_norm', 'RT_user_norm', 'Metacritic_norm', 'Metacritic_user_nom',
       'IMDB_norm', 'RT_norm_round', 'RT_user_norm_round',
       'Metacritic_norm_round', 'Metacritic_user_norm_round',
       'IMDB_norm_round', 'Fandango_Difference'],
      dtype='object')

In [29]:
# utilisation des crochets pour filtrer les colonnes de la condition float_columns
float_df = fandango_films[float_columns]
float_df

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),7.1,7.8,5.0,4.5,3.70,4.30,3.30,3.55,3.90,3.5,4.5,3.5,3.5,4.0,0.5
Cinderella (2015),7.5,7.1,5.0,4.5,4.25,4.00,3.35,3.75,3.55,4.5,4.0,3.5,4.0,3.5,0.5
Ant-Man (2015),8.1,7.8,5.0,4.5,4.00,4.50,3.20,4.05,3.90,4.0,4.5,3.0,4.0,4.0,0.5
Do You Believe? (2015),4.7,5.4,5.0,4.5,0.90,4.20,1.10,2.35,2.70,1.0,4.0,1.0,2.5,2.5,0.5
Hot Tub Time Machine 2 (2015),3.4,5.1,3.5,3.0,0.70,1.40,1.45,1.70,2.55,0.5,1.5,1.5,1.5,2.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mr. Holmes (2015),7.9,7.4,4.0,4.0,4.35,3.90,3.35,3.95,3.70,4.5,4.0,3.5,4.0,3.5,0.0
'71 (2015),7.5,7.2,3.5,3.5,4.85,4.10,4.15,3.75,3.60,5.0,4.0,4.0,4.0,3.5,0.0
"Two Days, One Night (2014)",8.8,7.4,3.5,3.5,4.85,3.90,4.45,4.40,3.70,5.0,4.0,4.5,4.5,3.5,0.0
Gett: The Trial of Viviane Amsalem (2015),7.3,7.8,3.5,3.5,5.00,4.05,4.50,3.65,3.90,5.0,4.0,4.5,3.5,4.0,0.0
"Kumiko, The Treasure Hunter (2015)",6.4,6.7,3.5,3.5,4.35,3.15,3.40,3.20,3.35,4.5,3.0,3.5,3.0,3.5,0.0

In [30]:
deviations = float_df.apply(lambda x: np.std(x))

In [32]:
#On applique la fonction std avec la méthode apply() sur le df float_df, qui va calculer l'écart type de chaque colonne
# dans l'annotation le x est un objet Series et correspond à chaque colonne
# ce qui signifie : applique pour chaque x la fonction std de calcule de l'écart type.
# cela retourne un objet Series contenant les écarts types pour chaque colonne

In [33]:
print(deviations)

Metacritic_User               1.505529
IMDB                          0.955447
Fandango_Stars                0.538532
Fandango_Ratingvalue          0.501106
RT_norm                       1.503265
RT_user_norm                  0.997787
Metacritic_norm               0.972522
Metacritic_user_nom           0.752765
IMDB_norm                     0.477723
RT_norm_round                 1.509404
RT_user_norm_round            1.003559
Metacritic_norm_round         0.987561
Metacritic_user_norm_round    0.785412
IMDB_norm_round               0.501043
Fandango_Difference           0.152141
dtype: float64

* Obtenir le dataframe float_df que j'ai réalisé en exemple (qui retourne les colonnes décimales float64)
* Utiliser la méthode apply() sur ce dataframe float_df afin de diviser par 2 chaque valeur et assigner le résultat à la variable exo_df.
* Afficher les premières lignes du résultat.

In [34]:
types = fandango_films.dtypes
float_columns = types[types.values == "float64"].index
float_df = fandango_films[float_columns]

In [35]:
exo_df = float_df.apply(lambda x: x/2)
print(exo_df)

                                           Metacritic_User  IMDB  \
FILM
Avengers: Age of Ultron (2015)                        3.55  3.90
Cinderella (2015)                                     3.75  3.55
Ant-Man (2015)                                        4.05  3.90
Do You Believe? (2015)                                2.35  2.70
Hot Tub Time Machine 2 (2015)                         1.70  2.55
...                                                    ...   ...
Mr. Holmes (2015)                                     3.95  3.70
'71 (2015)                                            3.75  3.60
Two Days, One Night (2014)                            4.40  3.70
Gett: The Trial of Viviane Amsalem (2015)             3.65  3.90
Kumiko, The Treasure Hunter (2015)                    3.20  3.35

                                           Fandango_Stars  \
FILM
Avengers: Age of Ultron (2015)                       2.50
Cinderella (2015)                                    2.50
Ant-Man (2015)                                       2.50
Do You Believe? (2015)                               2.50
Hot Tub Time Machine 2 (2015)                        1.75
...                                                   ...
Mr. Holmes (2015)                                    2.00
'71 (2015)                                           1.75
Two Days, One Night (2014)                           1.75
Gett: The Trial of Viviane Amsalem (2015)            1.75
Kumiko, The Treasure Hunter (2015)                   1.75

                                           Fandango_Ratingvalue  RT_norm  \
FILM
Avengers: Age of Ultron (2015)                             2.25    1.850
Cinderella (2015)                                          2.25    2.125
Ant-Man (2015)                                             2.25    2.000
Do You Believe? (2015)                                     2.25    0.450
Hot Tub Time Machine 2 (2015)                              1.50    0.350
...                                                         ...      ...
Mr. Holmes (2015)                                          2.00    2.175
'71 (2015)                                                 1.75    2.425
Two Days, One Night (2014)                                 1.75    2.425
Gett: The Trial of Viviane Amsalem (2015)                  1.75    2.500
Kumiko, The Treasure Hunter (2015)                         1.75    2.175

                                           RT_user_norm  Metacritic_norm  \
FILM
Avengers: Age of Ultron (2015)                    2.150            1.650
Cinderella (2015)                                 2.000            1.675
Ant-Man (2015)                                    2.250            1.600
Do You Believe? (2015)                            2.100            0.550
Hot Tub Time Machine 2 (2015)                     0.700            0.725
...                                                 ...              ...
Mr. Holmes (2015)                                 1.950            1.675
'71 (2015)                                        2.050            2.075
Two Days, One Night (2014)                        1.950            2.225
Gett: The Trial of Viviane Amsalem (2015)         2.025            2.250
Kumiko, The Treasure Hunter (2015)                1.575            1.700

                                           Metacritic_user_nom  IMDB_norm  \
FILM
Avengers: Age of Ultron (2015)                           1.775      1.950
Cinderella (2015)                                        1.875      1.775
Ant-Man (2015)                                           2.025      1.950
Do You Believe? (2015)                                   1.175      1.350
Hot Tub Time Machine 2 (2015)                            0.850      1.275
...                                                        ...        ...
Mr. Holmes (2015)                                        1.975      1.850
'71 (2015)                                               1.875      1.800
Two Days, One Night (2014)                               2.200      1.850
Gett: The Trial of Viviane Amsalem (2015)                1.825      1.950
Kumiko, The Treasure Hunter (2015)                       1.600      1.675

                                           RT_norm_round  RT_user_norm_round  \
FILM
Avengers: Age of Ultron (2015)                      1.75                2.25
Cinderella (2015)                                   2.25                2.00
Ant-Man (2015)                                      2.00                2.25
Do You Believe? (2015)                              0.50                2.00
Hot Tub Time Machine 2 (2015)                       0.25                0.75
...                                                  ...                 ...
Mr. Holmes (2015)                                   2.25                2.00
'71 (2015)                                          2.50                2.00
Two Days, One Night (2014)                          2.50                2.00
Gett: The Trial of Viviane Amsalem (2015)           2.50                2.00
Kumiko, The Treasure Hunter (2015)                  2.25                1.50

                                           Metacritic_norm_round  \
FILM
Avengers: Age of Ultron (2015)                              1.75
Cinderella (2015)                                           1.75
Ant-Man (2015)                                              1.50
Do You Believe? (2015)                                      0.50
Hot Tub Time Machine 2 (2015)                               0.75
...                                                          ...
Mr. Holmes (2015)                                           1.75
'71 (2015)                                                  2.00
Two Days, One Night (2014)                                  2.25
Gett: The Trial of Viviane Amsalem (2015)                   2.25
Kumiko, The Treasure Hunter (2015)                          1.75

                                           Metacritic_user_norm_round  \
FILM
Avengers: Age of Ultron (2015)                                   1.75
Cinderella (2015)                                                2.00
Ant-Man (2015)                                                   2.00
Do You Believe? (2015)                                           1.25
Hot Tub Time Machine 2 (2015)                                    0.75
...                                                               ...
Mr. Holmes (2015)                                                2.00
'71 (2015)                                                       2.00
Two Days, One Night (2014)                                       2.25
Gett: The Trial of Viviane Amsalem (2015)                        1.75
Kumiko, The Treasure Hunter (2015)                               1.50

                                           IMDB_norm_round  \
FILM
Avengers: Age of Ultron (2015)                        2.00
Cinderella (2015)                                     1.75
Ant-Man (2015)                                        2.00
Do You Believe? (2015)                                1.25
Hot Tub Time Machine 2 (2015)                         1.25
...                                                    ...
Mr. Holmes (2015)                                     1.75
'71 (2015)                                            1.75
Two Days, One Night (2014)                            1.75
Gett: The Trial of Viviane Amsalem (2015)             2.00
Kumiko, The Treasure Hunter (2015)                    1.75

                                           Fandango_Difference
FILM
Avengers: Age of Ultron (2015)                            0.25
Cinderella (2015)                                         0.25
Ant-Man (2015)                                            0.25
Do You Believe? (2015)                                    0.25
Hot Tub Time Machine 2 (2015)                             0.25
...                                                        ...
Mr. Holmes (2015)                                         0.00
'71 (2015)                                                0.00
Two Days, One Night (2014)                                0.00
Gett: The Trial of Viviane Amsalem (2015)                 0.00
Kumiko, The Treasure Hunter (2015)                        0.00

[146 rows x 15 columns]

## Méthode Apply() sur les lignes d'un DataFrame

In [36]:
# pour appliquer une fonction sur toutes les lignes d'un df, il peut utiliser le paramètre axis et le fixer à 1

In [37]:
# apply(function, axis=1)

In [38]:
rt_mt_user = float_df[["RT_user_norm", "Metacritic_user_nom"]]
rt_mt_user

                                           RT_user_norm  Metacritic_user_nom
FILM
Avengers: Age of Ultron (2015)                     4.30                 3.55
Cinderella (2015)                                  4.00                 3.75
Ant-Man (2015)                                     4.50                 4.05
Do You Believe? (2015)                             4.20                 2.35
Hot Tub Time Machine 2 (2015)                      1.40                 1.70
...                                                 ...                  ...
Mr. Holmes (2015)                                  3.90                 3.95
'71 (2015)                                         4.10                 3.75
Two Days, One Night (2014)                         3.90                 4.40
Gett: The Trial of Viviane Amsalem (2015)          4.05                 3.65
Kumiko, The Treasure Hunter (2015)                 3.15                 3.20

[146 rows x 2 columns]

In [39]:
rt_mt_user.apply(lambda x: np.std(x), axis=1)

FILM
Avengers: Age of Ultron (2015)               0.375
Cinderella (2015)                            0.125
Ant-Man (2015)                               0.225
Do You Believe? (2015)                       0.925
Hot Tub Time Machine 2 (2015)                0.150
                                             ...
Mr. Holmes (2015)                            0.025
'71 (2015)                                   0.175
Two Days, One Night (2014)                   0.250
Gett: The Trial of Viviane Amsalem (2015)    0.200
Kumiko, The Treasure Hunter (2015)           0.025
Length: 146, dtype: float64

   * Utiliser la méthode apply() pour calculer la moyenne (méthode mean() de la librarie Numpy) des valeurs de chaque film pour "RT_user_norm" et "metacritic_user_nom" puis assigner le résultat à la varible rt_mt_means.
   * Afficher les 5 premières valeurs de rt_mt_ means.

In [40]:
import numpy as np

In [41]:
rt_mt_user = float_df[["RT_user_norm", "Metacritic_user_nom"]]

In [45]:
rt_mt_means = rt_mt_user.apply(lambda x: np.mean(x), axis=1)
print(rt_mt_means[0:5])

FILM
Avengers: Age of Ultron (2015)    3.925
Cinderella (2015)                 3.875
Ant-Man (2015)                    4.275
Do You Believe? (2015)            3.275
Hot Tub Time Machine 2 (2015)     1.550
dtype: float64